/* Generated By:JJTree: Do not edit this line. ASTAccounts.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAccounts extends SimpleNode {
  public ASTAccounts(int id) {
    super(id);
  }

  public ASTAccounts(Hbl p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=460d463d0782065dea026583045a0cb0 (do not edit this line) */
