/* Generated By:JJTree: Do not edit this line. ASTAccountSpec.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAccountSpec extends SimpleNode {
  private String name;
  private String number;

  public ASTAccountSpec(int id) {
    super(id);
  }

  public ASTAccountSpec(Hbl p, int id) {
    super(p, id);
  }

  public void setName(String n) {
    name = n;
  }

  public void setNumber(String n) {
    number = n;
  }

}
/* JavaCC - OriginalChecksum=c95a325e02af29d365bd8e19d782da44 (do not edit this line) */
