/* Generated By:JJTree: Do not edit this line. ASTDate.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDate extends SimpleNode {
  public ASTDate(int id) {
    super(id);
  }

  public ASTDate(Hbl p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e8aa662c6d66a083d642ac06f60ff5a4 (do not edit this line) */
