/* Generated By:JJTree: Do not edit this line. ASTDDSpec.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDDSpec extends AbstractPoolSpec {
  public ASTDDSpec(int id) {
    super(id);
  }

  public ASTDDSpec(Hbl p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ea3773a618d06850b9bdb85d52e7465e (do not edit this line) */
