/* Generated By:JJTree: Do not edit this line. ASTDate.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
import javax.json.*;
public
class ASTDate extends SimpleNode {
  private Integer year;
  private Integer month;
  private Integer day;

  public ASTDate(int id) {
    super(id);
  }

  public ASTDate(Hbl p, int id) {
    super(p, id);
  }

  public void setDate(Integer y, Integer m, Integer d) {
    year = y;
    month = m;
    day = d;
  }

  public void generateSpecifics(JsonObjectBuilder builder) {
    builder.add("date", year + "-" + month + "-" + day);
  }

  public String toString() {
    return year.toString() + "-" + month.toString() + "-" + day.toString();
  }


}
/* JavaCC - OriginalChecksum=e8aa662c6d66a083d642ac06f60ff5a4 (do not edit this line) */
