/* Generated By:JJTree: Do not edit this line. ASTHorseSpec.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
import java.util.HashSet;
import javax.json.*;
public
class ASTHorseSpec extends SimpleNode {
  private String name;
  private Integer rank;
  public static HashSet<String> horseNames = new HashSet<String>();

  public ASTHorseSpec(int id) {
    super(id);
  }

  public ASTHorseSpec(Hbl p, int id) {
    super(p, id);
  }

  public void setName(String n) {
    name = n;
    if (horseNames.contains(name)) {
      ParseException.setSemanticError("A horse with name " + name + " is already defined.");
      parser.error(parser.generateParseException().getMessage());
    } else {
      horseNames.add(name);
    }
  }

  public void setRank(Integer r) {
    rank = r;
  }

  public void generateSpecifics(JsonObjectBuilder builder) {
    builder.add("name", name);
    builder.add("rank", rank);
  }
}
/* JavaCC - OriginalChecksum=ed18107cf54540aa4964dc61102f92c3 (do not edit this line) */
