/* Generated By:JJTree: Do not edit this line. ASTHorseSpec.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTHorseSpec extends SimpleNode {
  public ASTHorseSpec(int id) {
    super(id);
  }

  public ASTHorseSpec(Hbl p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ed18107cf54540aa4964dc61102f92c3 (do not edit this line) */
