/* Generated By:JJTree: Do not edit this line. ASTHorseSpec.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
import javax.json.*;
public
class ASTHorseSpec extends SimpleNode {
  private String rank;

  public ASTHorseSpec(int id) {
    super(id);
  }

  public ASTHorseSpec(Hbl p, int id) {
    super(p, id);
  }

  public void setRank(String r) {
    rank = r;
  }

  public void generateSpecifics(JsonObjectBuilder builder) {
    builder.add("rank", rank);
  }
}
/* JavaCC - OriginalChecksum=ed18107cf54540aa4964dc61102f92c3 (do not edit this line) */
