/* Generated By:JJTree: Do not edit this line. ASTHorseSelectionVxy.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
import javax.json.*;
import java.util.List;
import java.util.ArrayList;
public
class ASTHorseSelectionVxy extends SimpleNode {
  private Integer race;
  private List<Integer> horses = new ArrayList<Integer>();
  private List<Integer> reserves = new ArrayList<Integer>();
  private Boolean fortunaSelect = false;

  public ASTHorseSelectionVxy(int id) {
    super(id);
  }

  public ASTHorseSelectionVxy(Hbl p, int id) {
    super(p, id);
  }

  public void setRace(Integer r) {
    race = r;
  }

  public void addHorse(Integer h) {
    horses.add(h);
  }

  public void addReserve(Integer r) {
    reserves.add(r);
  }

  public void setFortunaSelect(Boolean val) {
    fortunaSelect = val;
  }

  public void generateSpecifics(JsonObjectBuilder builder) {
    builder.add("race", race);
    if (fortunaSelect) {
      builder.add("fortunaSelect", fortunaSelect);
    }
    final JsonArrayBuilder myBuilder = Json.createArrayBuilder();
    horses.forEach((horse) -> {
      myBuilder.add(horse);
    });
    builder.add("horses", myBuilder.build());

    final JsonArrayBuilder myBuilder2 = Json.createArrayBuilder();
    reserves.forEach((reserve) -> {
      myBuilder2.add(reserve);
    });
    builder.add("reserves", myBuilder2.build());
  }

}
/* JavaCC - OriginalChecksum=68ddfbde805d7b63e09f06f1b48646fa (do not edit this line) */
