/* Generated By:JJTree: Do not edit this line. ASTLegList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLegList extends SimpleNode {
  public ASTLegList(int id) {
    super(id);
  }

  public ASTLegList(Hbl p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f6fae3fe3e12f9cdfbff2ca8b48c0389 (do not edit this line) */
