/* Generated By:JJTree: Do not edit this line. ASTLegSpec.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLegSpec extends SimpleNode {
  public ASTLegSpec(int id) {
    super(id);
  }

  public ASTLegSpec(Hbl p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cd01ac894fd7a6ee7ec9c7dd5dccca69 (do not edit this line) */
