/* Generated By:JJTree: Do not edit this line. ASTMeeting.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMeeting extends SimpleNode {
  public ASTMeeting(int id) {
    super(id);
  }

  public ASTMeeting(Hbl p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2607718fc99ec42de0641dee96a7094f (do not edit this line) */
