/* Generated By:JJTree: Do not edit this line. ASTName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
import javax.json.*;
public
class ASTName extends SimpleNode {
  private String name;

  public ASTName(int id) {
    super(id);
  }

  public ASTName(Hbl p, int id) {
    super(p, id);
  }

  public void setName(String n) {
    name = n;
  }

  public void generateSpecifics(JsonObjectBuilder builder) {
    builder.add("name", name);
  }

  public String getName() {
      return name;
  }

}
/* JavaCC - OriginalChecksum=47d8fdd92350a44c5583751480b802ce (do not edit this line) */
