/* Generated By:JJTree: Do not edit this line. ASTProgram.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
import javax.json.*;
public
class ASTProgram extends SimpleNode {
  private String track;
  private String date;

  public ASTProgram(int id) {
    super(id);
  }

  public ASTProgram(Hbl p, int id) {
    super(p, id);
  }

  public void setTrack(String t) {
    track = t;
  }

  public void setDate(String d) {
    date = d;
  }

  public void generateSpecifics(JsonObjectBuilder builder) {
    builder.add("track", track);
    builder.add("date", date);
  }

}
/* JavaCC - OriginalChecksum=ed62792abe71dd564ee3dcdd5ed738e3 (do not edit this line) */
