/* Generated By:JJTree: Do not edit this line. ASTPoolSpecs.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPoolSpecs extends SimpleNode {
  public ASTPoolSpecs(int id) {
    super(id);
  }

  public ASTPoolSpecs(Hbl p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=82dd77ff1d51c8d0c653a7b2d775d899 (do not edit this line) */
