/* Generated By:JJTree: Do not edit this line. ASTRaceDay.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTRaceDay extends SimpleNode {
  public ASTRaceDay(int id) {
    super(id);
  }

  public ASTRaceDay(Hbl p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e0753f2a2ded25863f07d6e8df14db06 (do not edit this line) */
