/* Generated By:JJTree: Do not edit this line. ASTRaceDay.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
import javax.json.*;
public
class ASTRaceDay extends SimpleNode {
  private String track;
  private String date;
  public ASTRaceDay(int id) {
    super(id);
  }

  public ASTRaceDay(Hbl p, int id) {
    super(p, id);
  }

  public void setTrack(String t) {
    track = t;
  }

  public void setDate(String d) {
    date = d;
  }

  public void generateSpecifics(JsonObjectBuilder builder) {
    builder.add("track", track);
    builder.add("date", date);
  }
}
/* JavaCC - OriginalChecksum=e0753f2a2ded25863f07d6e8df14db06 (do not edit this line) */
