/* Generated By:JJTree: Do not edit this line. ASTStartList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStartList extends SimpleNode {
  public ASTStartList(int id) {
    super(id);
  }

  public ASTStartList(Hbl p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4f5b803f8c0ff227a472baab8989a885 (do not edit this line) */
