/* Generated By:JJTree: Do not edit this line. ASTTrackSpec.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
import java.util.HashSet;
import javax.json.*;
public
class ASTTrackSpec extends SimpleNode {
  private String name;
  public static HashSet<String> trackNames = new HashSet<String>();

  public ASTTrackSpec(int id) {
    super(id);
  }

  public ASTTrackSpec(Hbl p, int id) {
    super(p, id);
  }

  public void setName(String n) {
    name = n;
    if (trackNames.contains(name)) {
      ParseException.setSemanticError("A track with name " + name + " is already defined.");
      parser.error(parser.generateParseException().getMessage());
    } else {
      trackNames.add(name);
    }
  }

  public void generateSpecifics(JsonObjectBuilder builder) {
    builder.add("name", name);
  }

}
/* JavaCC - OriginalChecksum=3855e17daffdcbd9208cbc1545e7f586 (do not edit this line) */
