/* Generated By:JJTree: Do not edit this line. ASTTracks.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTTracks extends SimpleNode {
  public ASTTracks(int id) {
    super(id);
  }

  public ASTTracks(Hbl p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b5e27d1ef40639890ad6bf0c0a121c1f (do not edit this line) */
