/* Generated By:JJTree: Do not edit this line. ASTTrackSpec.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
import javax.json.*;
public
class ASTTrackSpec extends SimpleNode {
  private String name;

  public ASTTrackSpec(int id) {
    super(id);
  }

  public ASTTrackSpec(Hbl p, int id) {
    super(p, id);
  }

  public void setName(String n) {
    name = n;
  }

  public void generateSpecifics(JsonObjectBuilder builder) {
    builder.add("name", name);
  }

}
/* JavaCC - OriginalChecksum=3855e17daffdcbd9208cbc1545e7f586 (do not edit this line) */
