/* Generated By:JJTree: Do not edit this line. ASTV75Bet.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
import javax.json.*;
public
class ASTV75Bet extends SimpleNode {
  private String betID;
  private String accountID;
  private Boolean boost;
  private Integer multiplier;
  private Integer amount;
  private Boolean fortuna=false;


  public ASTV75Bet(int id) {
    super(id);
  }

  public ASTV75Bet(Hbl p, int id) {
    super(p, id);
  }

  public void setAccountID(String id) {
    accountID = id;
  }

  public void setBetID(String id) {
    betID = id;
  }

  public void setBoost(Boolean b) {
    boost = b;
  }

  public void setMultiplier(Integer m) {
    multiplier = m;
  }

  public void setAmount(Integer a) {
    amount = a;
  }

  public void setFortuna(Boolean f) {
    fortuna = f;
  }

  public void generateSpecifics(JsonObjectBuilder builder) {
    builder.add("betID", betID);
    if (fortuna) {
      builder.add("fortuna", fortuna);
      builder.add("amount", amount);
    } else {
      builder.add("multiplier", multiplier);
    }
    builder.add("boost", boost);
    if (accountID != null) {
      builder.add("accountID", accountID);
    }
  }

}
/* JavaCC - OriginalChecksum=fe53fa5da73ef54c6f94e0a3224ac7a9 (do not edit this line) */
