/* Generated By:JJTree&JavaCC: Do not edit this line. HblConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HblConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PERIOD = 15;
  /** RegularExpression Id. */
  int COMMA = 16;
  /** RegularExpression Id. */
  int COLON = 17;
  /** RegularExpression Id. */
  int DASH = 18;
  /** RegularExpression Id. */
  int LEFT_PAREN = 19;
  /** RegularExpression Id. */
  int RIGHT_PAREN = 20;
  /** RegularExpression Id. */
  int NUMBER = 21;
  /** RegularExpression Id. */
  int ACCOUNTS = 22;
  /** RegularExpression Id. */
  int HORSES = 23;
  /** RegularExpression Id. */
  int TRACKS = 24;
  /** RegularExpression Id. */
  int INCLUDE = 25;
  /** RegularExpression Id. */
  int MEETING = 26;
  /** RegularExpression Id. */
  int RACEDAY = 27;
  /** RegularExpression Id. */
  int LEG = 28;
  /** RegularExpression Id. */
  int DD = 29;
  /** RegularExpression Id. */
  int V75 = 30;
  /** RegularExpression Id. */
  int IDENTIFIER = 31;
  /** RegularExpression Id. */
  int STRING_LITERAL = 32;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int FirstlineMultilineComment = 1;
  /** Lexical state. */
  int WithinMultilineComment = 2;
  /** Lexical state. */
  int LastlineMultilineComment = 3;
  /** Lexical state. */
  int SinglelineComment = 4;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"---\"",
    "\"\\n\"",
    "<token of kind 3>",
    "\"---\"",
    "<token of kind 5>",
    "\"\\n\"",
    "<token of kind 7>",
    "\"--\"",
    "\"\\n\"",
    "<token of kind 10>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\".\"",
    "\",\"",
    "\":\"",
    "\"-\"",
    "\"(\"",
    "\")\"",
    "<NUMBER>",
    "\"Accounts:\"",
    "\"Horses:\"",
    "\"Tracks:\"",
    "\"Include:\"",
    "\"Meeting:\"",
    "\"RaceDay:\"",
    "\"Leg\"",
    "\"DD:\"",
    "\"V75:\"",
    "<IDENTIFIER>",
    "<STRING_LITERAL>",
  };

}
