/* Generated By:JavaCC: Do not edit this line. HblTreeConstants.java Version 5.0 */
public interface HblTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTINCLUDE = 2;
  public int JJTACCOUNTSPEC = 3;
  public int JJTACCOUNTS = 4;
  public int JJTHORSESPEC = 5;
  public int JJTHORSES = 6;
  public int JJTTRACKSPEC = 7;
  public int JJTTRACKS = 8;
  public int JJTDDSPEC = 9;
  public int JJTLEGLIST = 10;
  public int JJTV75SPEC = 11;
  public int JJTLEGSPEC = 12;
  public int JJTMEETING = 13;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Include",
    "AccountSpec",
    "Accounts",
    "HorseSpec",
    "Horses",
    "TrackSpec",
    "Tracks",
    "DDSpec",
    "LegList",
    "V75Spec",
    "LegSpec",
    "Meeting",
  };
}
/* JavaCC - OriginalChecksum=d11ef2d0bbeed7910e9fdb6e415bc1fa (do not edit this line) */
