/* Generated By:JavaCC: Do not edit this line. HblTreeConstants.java Version 5.0 */
public interface HblTreeConstants
{
  public int JJTSTART = 0;
  public int JJTNAME = 1;
  public int JJTINCLUDE = 2;
  public int JJTACCOUNTSPEC = 3;
  public int JJTACCOUNTS = 4;
  public int JJTHORSESPEC = 5;
  public int JJTHORSES = 6;
  public int JJTTRACKSPEC = 7;
  public int JJTTRACKS = 8;
  public int JJTDATE = 9;
  public int JJTDDSPEC = 10;
  public int JJTLEGLIST = 11;
  public int JJTV75SPEC = 12;
  public int JJTPOOLSPECS = 13;
  public int JJTSTARTLIST = 14;
  public int JJTLEGSPEC = 15;
  public int JJTLEGSPECS = 16;
  public int JJTMEETING = 17;


  public String[] jjtNodeName = {
    "Start",
    "Name",
    "Include",
    "AccountSpec",
    "Accounts",
    "HorseSpec",
    "Horses",
    "TrackSpec",
    "Tracks",
    "Date",
    "DDSpec",
    "LegList",
    "V75Spec",
    "PoolSpecs",
    "StartList",
    "LegSpec",
    "LegSpecs",
    "Meeting",
  };
}
/* JavaCC - OriginalChecksum=b19e8fe8e43025394b28e82ac00e5b72 (do not edit this line) */
