/* Generated By:JavaCC: Do not edit this line. HblTreeConstants.java Version 5.0 */
public interface HblTreeConstants
{
  public int JJTSTART = 0;
  public int JJTNAME = 1;
  public int JJTINCLUDE = 2;
  public int JJTACCOUNTSPEC = 3;
  public int JJTACCOUNTS = 4;
  public int JJTHORSESPEC = 5;
  public int JJTHORSES = 6;
  public int JJTTRACKSPEC = 7;
  public int JJTTRACKS = 8;
  public int JJTDATE = 9;
  public int JJTDDSPEC = 10;
  public int JJTLEGLIST = 11;
  public int JJTV75SPEC = 12;
  public int JJTPOOLSPECS = 13;
  public int JJTSTARTLIST = 14;
  public int JJTLEGSPEC = 15;
  public int JJTLEGSPECS = 16;
  public int JJTPROGRAM = 17;
  public int JJTMEETING = 18;
  public int JJTLEGRESULT = 19;
  public int JJTRESULTLIST = 20;
  public int JJTRESULTENTRY = 21;
  public int JJTTIE = 22;
  public int JJTBET = 23;
  public int JJTDDBET = 24;
  public int JJTHORSESELECTION = 25;
  public int JJTV75BET = 26;
  public int JJTMULTIPLIER = 27;


  public String[] jjtNodeName = {
    "Start",
    "Name",
    "Include",
    "AccountSpec",
    "Accounts",
    "HorseSpec",
    "Horses",
    "TrackSpec",
    "Tracks",
    "Date",
    "DDSpec",
    "LegList",
    "V75Spec",
    "PoolSpecs",
    "StartList",
    "LegSpec",
    "LegSpecs",
    "Program",
    "Meeting",
    "LegResult",
    "ResultList",
    "ResultEntry",
    "Tie",
    "Bet",
    "DDBet",
    "HorseSelection",
    "V75Bet",
    "Multiplier",
  };
}
/* JavaCC - OriginalChecksum=1136a90ff3f5d93121223b3e4d6c1e25 (do not edit this line) */
