/* Generated By:JJTree: Do not edit this line. ASTAnyNonIncludeToken.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package se.atg.tabs.hblcompiler;

public
class ASTAnyNonIncludeToken extends SimpleNode {
  public ASTAnyNonIncludeToken(int id) {
    super(id);
  }

  public ASTAnyNonIncludeToken(Hbl p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0a1c521305d44e4aa39b3581d9034e7d (do not edit this line) */
