/* Generated By:JJTree: Do not edit this line. ASTBet.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
import javax.json.*;
public
class ASTBet extends SimpleNode {
  public ASTBet(int id) {
    super(id);
  }

  public ASTBet(Hbl p, int id) {
    super(p, id);
  }

  protected JsonObject generateThis(JsonArray children) {
    return children.getJsonObject(0);
  }


}
/* JavaCC - OriginalChecksum=c806792377ef1e602061709a4961838e (do not edit this line) */
