/* Generated By:JJTree: Do not edit this line. ASTHandleParseException.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package se.atg.tabs.hblcompiler;

public
class ASTHandleParseException extends SimpleNode {
  public ASTHandleParseException(int id) {
    super(id);
  }

  public ASTHandleParseException(Hbl p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ada048c4d01dfc09a75383c31e262414 (do not edit this line) */
