/* Generated By:JJTree: Do not edit this line. ASTHandleParseException.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTHandleParseException extends SimpleNode {
  public ASTHandleParseException(int id) {
    super(id);
  }

  public ASTHandleParseException(Hbl p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8b08a553dedb7d77c6c0bc8257af7047 (do not edit this line) */
