/* Generated By:JJTree: Do not edit this line. ASTHorses.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTHorses extends SimpleNode {
  public ASTHorses(int id) {
    super(id);
  }

  public ASTHorses(Hbl p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f6e37e150b44d7a6c710b04e41d814f0 (do not edit this line) */
