/* Generated By:JJTree: Do not edit this line. ASTHorses.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package se.atg.tabs.hblcompiler;

public
class ASTHorses extends SimpleNode {
  public ASTHorses(int id) {
    super(id);
  }

  public ASTHorses(Hbl p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d928091020ab06494d3aef6656d21ef1 (do not edit this line) */
