/* Generated By:JJTree: Do not edit this line. ASTPreprocess.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package se.atg.tabs.hblcompiler;

public
class ASTPreprocess extends SimpleNode {
  public ASTPreprocess(int id) {
    super(id);
  }

  public ASTPreprocess(Hbl p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=89620f1c6483b282d106c24107136f0d (do not edit this line) */
