/* Generated By:JJTree: Do not edit this line. ASTResultEntry.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package se.atg.tabs.hblcompiler;
import java.util.List;
import java.util.ArrayList;
public
class ASTResultEntry extends SimpleNode {
  private List<Integer> horses;
  public ASTResultEntry(int id) {
    super(id);
  }

  public ASTResultEntry(Hbl p, int id) {
    super(p, id);
  }

  public void setEntry(Integer singleHorse) {
    horses = new ArrayList<Integer>();
    horses.add(singleHorse);
  }

  public void setEntry(List<Integer> tiedHorses) {
    horses = tiedHorses;
  }

  public List<Integer> getHorses() {
    return horses;
  }

  public Boolean skipNode() {
    return true;
  }
}
/* JavaCC - OriginalChecksum=2c4540c0458fb93bb46688209d43ff6a (do not edit this line) */
