/* Generated By:JJTree: Do not edit this line. ASTStart.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package se.atg.tabs.hblcompiler;

public
class ASTStart extends SimpleNode {
  public ASTStart(int id) {
    super(id);
  }

  public ASTStart(Hbl p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=66c881e9ecc81ff2d13c0c4a12a7d079 (do not edit this line) */
