/* Generated By:JJTree: Do not edit this line. ASTTracks.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package se.atg.tabs.hblcompiler;
public
class ASTTracks extends SimpleNode {
  public ASTTracks(int id) {
    super(id);
  }

  public ASTTracks(Hbl p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=487a34892bec8428b663a9d1d81c7ac1 (do not edit this line) */
