/* Generated By:JJTree: Do not edit this line. ASTTie.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package se.atg.tabs.hblcompiler;
import javax.json.*;
import java.util.List;
import java.util.ArrayList;
public
class ASTTie extends SimpleNode {
  private ArrayList<Integer> horses = new ArrayList<Integer>();

  public ASTTie(int id) {
    super(id);
  }

  public ASTTie(Hbl p, int id) {
    super(p, id);
  }

  public void addHorse(Integer horse) {
    horses.add(horse);
  }

  public List<Integer> getHorses() {
    return horses;
  }

  public Boolean skipNode() {
    return true;
  }

}
/* JavaCC - OriginalChecksum=78b37d6ad83cc574cf3defd0acb8245e (do not edit this line) */
