/* Generated By:JJTree: Do not edit this line. ASTV75Spec.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package se.atg.tabs.hblcompiler;

public
class ASTV75Spec extends AbstractPoolSpec {
  public ASTV75Spec(int id) {
    super(id);
  }

  public ASTV75Spec(Hbl p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d79c30a1ba14508b027620abd6e9fd2a (do not edit this line) */
