/* Generated By:JJTree&JavaCC: Do not edit this line. HblConstants.java */
package se.atg.tabs.hblcompiler;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HblConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PERIOD = 15;
  /** RegularExpression Id. */
  int COMMA = 16;
  /** RegularExpression Id. */
  int COLON = 17;
  /** RegularExpression Id. */
  int DASH = 18;
  /** RegularExpression Id. */
  int LEFT_PAREN = 19;
  /** RegularExpression Id. */
  int RIGHT_PAREN = 20;
  /** RegularExpression Id. */
  int NUMBER = 21;
  /** RegularExpression Id. */
  int ACCOUNTS = 22;
  /** RegularExpression Id. */
  int ACCOUNT = 23;
  /** RegularExpression Id. */
  int HORSES = 24;
  /** RegularExpression Id. */
  int TRACKS = 25;
  /** RegularExpression Id. */
  int INCLUDE = 26;
  /** RegularExpression Id. */
  int PROGRAM = 27;
  /** RegularExpression Id. */
  int MEETING = 28;
  /** RegularExpression Id. */
  int LEG = 29;
  /** RegularExpression Id. */
  int DD = 30;
  /** RegularExpression Id. */
  int V75 = 31;
  /** RegularExpression Id. */
  int BET = 32;
  /** RegularExpression Id. */
  int DD_1 = 33;
  /** RegularExpression Id. */
  int DD_2 = 34;
  /** RegularExpression Id. */
  int V75_1 = 35;
  /** RegularExpression Id. */
  int V75_2 = 36;
  /** RegularExpression Id. */
  int V75_3 = 37;
  /** RegularExpression Id. */
  int V75_4 = 38;
  /** RegularExpression Id. */
  int V75_5 = 39;
  /** RegularExpression Id. */
  int V75_6 = 40;
  /** RegularExpression Id. */
  int V75_7 = 41;
  /** RegularExpression Id. */
  int X1 = 42;
  /** RegularExpression Id. */
  int X2 = 43;
  /** RegularExpression Id. */
  int X3 = 44;
  /** RegularExpression Id. */
  int X4 = 45;
  /** RegularExpression Id. */
  int X5 = 46;
  /** RegularExpression Id. */
  int X10 = 47;
  /** RegularExpression Id. */
  int X20 = 48;
  /** RegularExpression Id. */
  int X50 = 49;
  /** RegularExpression Id. */
  int X100 = 50;
  /** RegularExpression Id. */
  int REPEAT = 51;
  /** RegularExpression Id. */
  int FORTUNA = 52;
  /** RegularExpression Id. */
  int RESERVES = 53;
  /** RegularExpression Id. */
  int FORTUNA_SELECT = 54;
  /** RegularExpression Id. */
  int ALL_HORSES = 55;
  /** RegularExpression Id. */
  int BOOST = 56;
  /** RegularExpression Id. */
  int IDENTIFIER = 57;
  /** RegularExpression Id. */
  int STRING_LITERAL = 58;
  /** RegularExpression Id. */
  int UNKNOWN = 59;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int FirstlineMultilineComment = 1;
  /** Lexical state. */
  int WithinMultilineComment = 2;
  /** Lexical state. */
  int LastlineMultilineComment = 3;
  /** Lexical state. */
  int SinglelineComment = 4;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"---\"",
    "\"\\n\"",
    "<token of kind 3>",
    "\"---\"",
    "<token of kind 5>",
    "\"\\n\"",
    "<token of kind 7>",
    "\"--\"",
    "\"\\n\"",
    "<token of kind 10>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\".\"",
    "\",\"",
    "\":\"",
    "\"-\"",
    "\"(\"",
    "\")\"",
    "<NUMBER>",
    "\"Accounts\"",
    "\"Account\"",
    "\"Horses\"",
    "\"Tracks\"",
    "\"Include\"",
    "\"Program\"",
    "\"Meeting\"",
    "\"Leg\"",
    "\"DD\"",
    "\"V75\"",
    "\"Bet\"",
    "\"DD-1\"",
    "\"DD-2\"",
    "\"V75-1\"",
    "\"V75-2\"",
    "\"V75-3\"",
    "\"V75-4\"",
    "\"V75-5\"",
    "\"V75-6\"",
    "\"V75-7\"",
    "\"X1\"",
    "\"X2\"",
    "\"X3\"",
    "\"X4\"",
    "\"X5\"",
    "\"X10\"",
    "\"X20\"",
    "\"X50\"",
    "\"X100\"",
    "\"Repeat\"",
    "\"Fortuna\"",
    "\"R\"",
    "\"F\"",
    "\"A\"",
    "\"Boost\"",
    "<IDENTIFIER>",
    "<STRING_LITERAL>",
    "<UNKNOWN>",
  };

}
