/* Generated By:JJTree&JavaCC: Do not edit this line. HblConstants.java */
package se.atg.tabs.hblcompiler;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HblConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PERIOD = 11;
  /** RegularExpression Id. */
  int DASH = 12;
  /** RegularExpression Id. */
  int LEFT_PAREN = 13;
  /** RegularExpression Id. */
  int RIGHT_PAREN = 14;
  /** RegularExpression Id. */
  int NUMBER = 15;
  /** RegularExpression Id. */
  int ACCOUNTS = 16;
  /** RegularExpression Id. */
  int ACCOUNT = 17;
  /** RegularExpression Id. */
  int HORSES = 18;
  /** RegularExpression Id. */
  int TRACKS = 19;
  /** RegularExpression Id. */
  int INCLUDE = 20;
  /** RegularExpression Id. */
  int PROGRAM = 21;
  /** RegularExpression Id. */
  int MEETING = 22;
  /** RegularExpression Id. */
  int LEG = 23;
  /** RegularExpression Id. */
  int DD_BET = 24;
  /** RegularExpression Id. */
  int V75_BET = 25;
  /** RegularExpression Id. */
  int DD_LEGS = 26;
  /** RegularExpression Id. */
  int V75_LEGS = 27;
  /** RegularExpression Id. */
  int BET = 28;
  /** RegularExpression Id. */
  int DD_1 = 29;
  /** RegularExpression Id. */
  int DD_2 = 30;
  /** RegularExpression Id. */
  int V75_1 = 31;
  /** RegularExpression Id. */
  int V75_2 = 32;
  /** RegularExpression Id. */
  int V75_3 = 33;
  /** RegularExpression Id. */
  int V75_4 = 34;
  /** RegularExpression Id. */
  int V75_5 = 35;
  /** RegularExpression Id. */
  int V75_6 = 36;
  /** RegularExpression Id. */
  int V75_7 = 37;
  /** RegularExpression Id. */
  int X1 = 38;
  /** RegularExpression Id. */
  int X2 = 39;
  /** RegularExpression Id. */
  int X3 = 40;
  /** RegularExpression Id. */
  int X4 = 41;
  /** RegularExpression Id. */
  int X5 = 42;
  /** RegularExpression Id. */
  int X10 = 43;
  /** RegularExpression Id. */
  int X20 = 44;
  /** RegularExpression Id. */
  int X50 = 45;
  /** RegularExpression Id. */
  int X100 = 46;
  /** RegularExpression Id. */
  int REPEAT = 47;
  /** RegularExpression Id. */
  int FORTUNA = 48;
  /** RegularExpression Id. */
  int RESERVES = 49;
  /** RegularExpression Id. */
  int FORTUNA_SELECT = 50;
  /** RegularExpression Id. */
  int ALL_HORSES = 51;
  /** RegularExpression Id. */
  int BOOST = 52;
  /** RegularExpression Id. */
  int IDENTIFIER = 53;
  /** RegularExpression Id. */
  int STRING_LITERAL = 54;
  /** RegularExpression Id. */
  int UNKNOWN = 55;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int WithinMultilineComment = 1;
  /** Lexical state. */
  int SinglelineComment = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"---\"",
    "\"---\"",
    "<token of kind 3>",
    "\"--\"",
    "\"\\n\"",
    "<token of kind 6>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\".\"",
    "\"-\"",
    "\"(\"",
    "\")\"",
    "<NUMBER>",
    "\"Accounts\"",
    "\"Account\"",
    "\"Horses\"",
    "\"Tracks\"",
    "\"Include\"",
    "\"Program\"",
    "\"Meeting\"",
    "\"Leg\"",
    "\"DD-Bet\"",
    "\"V75-Bet\"",
    "\"DD-Legs\"",
    "\"V75-Legs\"",
    "\"Bet\"",
    "\"DD-1\"",
    "\"DD-2\"",
    "\"V75-1\"",
    "\"V75-2\"",
    "\"V75-3\"",
    "\"V75-4\"",
    "\"V75-5\"",
    "\"V75-6\"",
    "\"V75-7\"",
    "\"X1\"",
    "\"X2\"",
    "\"X3\"",
    "\"X4\"",
    "\"X5\"",
    "\"X10\"",
    "\"X20\"",
    "\"X50\"",
    "\"X100\"",
    "\"Repeat\"",
    "\"Fortuna\"",
    "\"R\"",
    "\"F\"",
    "\"A\"",
    "\"Boost\"",
    "<IDENTIFIER>",
    "<STRING_LITERAL>",
    "<UNKNOWN>",
  };

}
