/* Generated By:JavaCC: Do not edit this line. HblTreeConstants.java Version 6.1_2 */
package se.atg.tabs.hblcompiler;

public interface HblTreeConstants
{
  public int JJTPREPROCESS = 0;
  public int JJTINCLUDE = 1;
  public int JJTANYNONINCLUDETOKEN = 2;
  public int JJTSTART = 3;
  public int JJTHANDLEPARSEEXCEPTION = 4;
  public int JJTNAME = 5;
  public int JJTACCOUNTSPEC = 6;
  public int JJTACCOUNTS = 7;
  public int JJTHORSESPEC = 8;
  public int JJTHORSES = 9;
  public int JJTTRACKSPEC = 10;
  public int JJTTRACKS = 11;
  public int JJTDATE = 12;
  public int JJTDDSPEC = 13;
  public int JJTLEGLIST = 14;
  public int JJTV75SPEC = 15;
  public int JJTPOOLSPECS = 16;
  public int JJTSTARTLIST = 17;
  public int JJTLEGSPEC = 18;
  public int JJTLEGSPECS = 19;
  public int JJTPROGRAM = 20;
  public int JJTMEETING = 21;
  public int JJTLEGRESULT = 22;
  public int JJTRESULTLIST = 23;
  public int JJTRESULTENTRY = 24;
  public int JJTTIE = 25;
  public int JJTBET = 26;
  public int JJTDDBET = 27;
  public int JJTHORSESELECTION = 28;
  public int JJTV75BET = 29;
  public int JJTMULTIPLIER = 30;


  public String[] jjtNodeName = {
    "Preprocess",
    "Include",
    "AnyNonIncludeToken",
    "Start",
    "HandleParseException",
    "Name",
    "AccountSpec",
    "Accounts",
    "HorseSpec",
    "Horses",
    "TrackSpec",
    "Tracks",
    "Date",
    "DDSpec",
    "LegList",
    "V75Spec",
    "PoolSpecs",
    "StartList",
    "LegSpec",
    "LegSpecs",
    "Program",
    "Meeting",
    "LegResult",
    "ResultList",
    "ResultEntry",
    "Tie",
    "Bet",
    "DDBet",
    "HorseSelection",
    "V75Bet",
    "Multiplier",
  };
}
/* JavaCC - OriginalChecksum=03a1bd302646b70ad348168f2d927af8 (do not edit this line) */
