/* Generated By:JavaCC: Do not edit this line. HblTreeConstants.java Version 5.0 */
public interface HblTreeConstants
{
  public int JJTSTART = 0;
  public int JJTHANDLEPARSEEXCEPTION = 1;
  public int JJTNAME = 2;
  public int JJTINCLUDE = 3;
  public int JJTACCOUNTSPEC = 4;
  public int JJTACCOUNTS = 5;
  public int JJTHORSESPEC = 6;
  public int JJTHORSES = 7;
  public int JJTTRACKSPEC = 8;
  public int JJTTRACKS = 9;
  public int JJTDATE = 10;
  public int JJTDDSPEC = 11;
  public int JJTLEGLIST = 12;
  public int JJTV75SPEC = 13;
  public int JJTPOOLSPECS = 14;
  public int JJTSTARTLIST = 15;
  public int JJTLEGSPEC = 16;
  public int JJTLEGSPECS = 17;
  public int JJTPROGRAM = 18;
  public int JJTMEETING = 19;
  public int JJTLEGRESULT = 20;
  public int JJTRESULTLIST = 21;
  public int JJTRESULTENTRY = 22;
  public int JJTTIE = 23;
  public int JJTBET = 24;
  public int JJTDDBET = 25;
  public int JJTHORSESELECTION = 26;
  public int JJTV75BET = 27;
  public int JJTMULTIPLIER = 28;


  public String[] jjtNodeName = {
    "Start",
    "HandleParseException",
    "Name",
    "Include",
    "AccountSpec",
    "Accounts",
    "HorseSpec",
    "Horses",
    "TrackSpec",
    "Tracks",
    "Date",
    "DDSpec",
    "LegList",
    "V75Spec",
    "PoolSpecs",
    "StartList",
    "LegSpec",
    "LegSpecs",
    "Program",
    "Meeting",
    "LegResult",
    "ResultList",
    "ResultEntry",
    "Tie",
    "Bet",
    "DDBet",
    "HorseSelection",
    "V75Bet",
    "Multiplier",
  };
}
/* JavaCC - OriginalChecksum=a902a487e13a2a9a51b1943d0fed3037 (do not edit this line) */
